# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DriveriOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
	platform :ios, '9.0'
  # Pods for DriveriOS
  pod 'PeerTalk', :git => 'https://github.com/rsms/peertalk'
end

target 'DrivermacOS' do
platform :osx, '10.13'
pod 'PeerTalk', :git => 'https://github.com/rsms/peertalk'
end
